version: '2'
services:
  postgres:
    image: 'postgres:latest'
    container_name: proyecto
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    volumes:
     - './postgres_data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
